### ISSUE TITLE
fix css styling on editor help modal

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#100]
**Which part of the project should be enhanced?**
the help modal in the editor

**Is your enhancement request related to a problem? Please describe.**
no

**Describe the solution you'd like**
Make the left side look like it would in the preview window.
Make the right side look like in the editor.
In the sidebar add space between cards

**Comment by mrdrogdrog** [comment]
Please check if this issue is still valid, because #197 introduced the markdown css rules.
