### ISSUE TITLE
add browser e2e tests

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#11]
we should add some kind of browser e2e tests to ensure the frontend behaves the way we think and that nobody breaks it in future commits

which framework should we use for this?

**Comment by SuperSandro2000** [comment]
https://www.cypress.io/ ?

**Comment by DerMolly** [comment]
Do you have any experience with this framework @SuperSandro2000 ?

**Comment by SuperSandro2000** [comment]
No but it seems promising.
