### ISSUE TITLE
Switch back to fork-awesome

### ISSUE THREAD

**Issue by SISheogorath** [codimd/react-client#112]
**Which part of the project should be enhanced?**
Icon fonts

**Is your enhancement request related to a problem? Please describe.**
We will need fork-awesome icons at least within documents. And generally speaking we already intentionally switched away from Font-awesome ages ago due to being not a project fitting our community project philosophy/the free software spirit: https://github.com/codimd/server/commit/5212bbf9c4bb14d0ee5f009512df0bb6f7a475d0

Details:
https://github.com/FortAwesome/Font-Awesome/issues/12199#issuecomment-362919956
https://github.com/FortAwesome/Font-Awesome/blob/master/.github/PULL_REQUEST_TEMPLATE.md

**Describe the solution you'd like**
Replace Font-Awesome with a community driven alternative like fork-awesome. We should avoid promoting proprietary software/… with CodiMD whenever possible.

**Describe alternatives you've considered**
None. This was already changed in CodiMD 1.3.0 and we should keep it that way as it would be a bad move to switch from a free software solution to a proprietary one.

**Additional context**
Nothing to add here.

**Comment by SuperSandro2000** [comment]
Just posting their pull request template so that it does not disappear silently:

```
<!--- WARNING Pull Requests made to this repository cannot be merged -->

I understand that:

- [ ] I'm submitting this PR for reference only. It shows an example of what I'd like to see changed but
  I understand that it will not be merged and I will not be listed as a contributor on this project.
```
