### ISSUE TITLE
Prepare change overview

### ISSUE THREAD

**Issue by SISheogorath** [codimd/react-client#174]
With the ongoing development and the fact that it first of all happens disconnected from the current frontend, we compose an overview of what has changed from the 1.6 UI/UX to the 2.0 UI/UX.

As we all notice that we fix something small here and there, but also introduce major changes, we should provide an overview on how people may have to adjust their workflow. For the 2.0 server-side that actually seems rather simple as we point people to the new API documentation and figure out what endpoints we removed due to the changes.

For the frontend we can either do an in-detail review once it's finished but will probably miss details or write kind of an ongoing changelog to keep things a bit organized.

**Comment by DerMolly** [comment]
I quite like the idea of a ongoing changelog.

**Comment by ccoenen** [comment]
On the server repository, we're following mostly this pattern here: https://keepachangelog.com/en/1.0.0/

**Comment by DerMolly** [comment]
The change log will most likely not contain the changes of 1.6.0 and prior, so we'll just start with a Unreleased 2.0.0?

**Comment by ErikMichelson** [comment]
Just for discussion: How about an in-app tutorial (tooltips like "These are your recently opened notes. Click this icon to switch to a table view.") that users may click through or skip?

**Comment by DerMolly** [comment]
I‘m not sure we currently need that. I hope our client is intuitive enough (at least for now).

**Comment by DerMolly** [comment]
Since we're actively doing the proposed procedure, I'll close this issue
