### ISSUE TITLE
show TOC in view mode and readd support for `[TOC]`

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#209]
# Describe the solution you'd like
The markdown preview should show an TOC again and render the token `[TOC]` in Markdown like in 1.6

## behavior in 1.6:
![grafik](https://user-images.githubusercontent.com/3978662/85168816-2e860000-b26b-11ea-9cec-7a9fdd0ccf3f.png)
## behavior currently in 2.0
![grafik](https://user-images.githubusercontent.com/3978662/85168846-38a7fe80-b26b-11ea-88cb-6959614009a9.png)

# Additional context
#### usage
https://github.com/codimd/server/blob/20a1563d7f81d0454533c569b6505c71a720956f/public/js/extra.js#L30
#### code
https://github.com/codimd/server/blob/master/public/vendor/md-toc.js
and maybe
https://github.com/yijian166/md-toc.js
( but our version seems to be developed further)
### extra code for TOC
https://github.com/codimd/server/blob/20a1563d7f81d0454533c569b6505c71a720956f/public/js/extra.js#L202-222
https://github.com/codimd/server/blob/20a1563d7f81d0454533c569b6505c71a720956f/public/js/extra.js#L656-681
### `[TOC]` Plugin
https://github.com/codimd/server/blob/20a1563d7f81d0454533c569b6505c71a720956f/public/js/extra.js#L1137-1142

**Comment by SISheogorath** [comment]
I did a major rewrite of the md-toc a while ago because it wasn't working properly when header levels were skipped.

https://github.com/codimd/server/commit/4fe062085324c50f2cfa062258559cf31858ef5f#diff-4babab6a1adf890932882b500583a095

It's not the most straight forward code, but solved some problems we had with the original implementation.

**Comment by mrdrogdrog** [comment]
I think the best practice would be to iterate over the generated react dom before we render it. Then we don't have to concat html code.

**Comment by mrdrogdrog** [comment]
But it's good to see a working implementation that we can translate into react code
