### ISSUE TITLE
reimplement synchronous scrolling 

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#212]
**Describe the solution you'd like**
The editor and preview windows should scroll synchronously again. We need to implement a (new) method to realize that. 

**Describe alternatives you've considered**
Since not re implementing this feature is not really an option, there is no real alternative.

**Additional context**
Currently this is done via many hidden Elements in the rendered DOM which show from which line in the markdown the elements originate from. 

**scrollspy initalization** 
https://github.com/codimd/server/blob/6462968e84e8d92292dd23764a9e558d7800147d/public/js/pretty.js#L85

**scrollspy extras removed**
https://github.com/codimd/server/blob/20a1563d7f81d0454533c569b6505c71a720956f/public/js/extra.js#L600

**smoothHashScroll function**
https://github.com/codimd/server/blob/20a1563d7f81d0454533c569b6505c71a720956f/public/js/extra.js#L781

**Comment by DerMolly** [comment]
Finally this is closed. :joy:

**Comment by mrdrogdrog** [comment]
![finally](https://thumbs.gfycat.com/FamousUnfoldedCusimanse-size_restricted.gif)
