### ISSUE TITLE
Readd syntax highlighting in render output

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#213]
**Describe the solution you'd like**

Codimd 1.6 uses Prism for syntax highlighting in the rendered markdown
![image](https://user-images.githubusercontent.com/6124140/85176835-0a321f80-b27b-11ea-98b2-954b63de7a40.png)

**Additional context**

https://github.com/codimd/server/blob/20a1563d7f81d0454533c569b6505c71a720956f/public/js/extra.js#L488

**Comment by SISheogorath** [comment]
It also uses highlightjs.

**Comment by mrdrogdrog** [comment]
Why does it use prism AND highlightjs? o.ö..

**Comment by SISheogorath** [comment]
iirc because either of them lacks of some highlighting for languages.

No matter what, that how it's currently implemented, I don't mind deciding for one of these with 2.0.

Might be helpful: https://github.com/codimd/server/pull/21/files

It already refactored the hightlight code and could be inspiration or reference on what's crazy with the 1.6.x code :)

**Comment by mrdrogdrog** [comment]
We compared the current state of highlightjs and prism. We came to the conclusion, that it would be the best choice to only support highlightjs.

**Comment by mrdrogdrog** [comment]
highlightjs doesn't support 'jsx', 'tiddlywiki' and 'mediawiki'. Do we really need these?

**Comment by SISheogorath** [comment]
I guess as with other things, dropping support for it, is as easy as adding it back again. For now I think we can drop them and if someone yells, the amount of work doesn't actually increase from the current state.

**Comment by mrdrogdrog** [comment]
In codimd 1.6 prism was also used for haskell, go and typescript and I think these are the more important languages. By now they were added to highlightjs.

So yes.. I would drop the remaining three and wait until there is a request.

**Comment by DerMolly** [comment]
We could check with highlightjs if they could add those three langauges...

**Comment by mrdrogdrog** [comment]
https://highlightjs.readthedocs.io/en/latest/language-requests.html
