### ISSUE TITLE
Re-add in-document navigation sidebar

### ISSUE THREAD

**Issue by ErikMichelson** [codimd/react-client#245]
**Describe the solution you'd like**
The in-document navigation as shown in the figure below should be added to the react-client.
![](https://user-images.githubusercontent.com/8719867/85213144-c4e51f00-b35a-11ea-82c6-03c905ee81bc.png)

**Additional context**
This issue requires basic workings on the scrollspy implementation.
The legacy code uses a `ul`-`li` list with some custom styles and `active` classes added by the scrollspy to open sub-menus.

**Comment by ccoenen** [comment]
It would be amazing if this was also available in edit mode, I added this proposal to #93.
