### ISSUE TITLE
Replace MathJax with KaTeX

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#252]
**What is your question?**
MathJax is rather cumbersome to package and likes it far more to load all the JS when needed. That's rather unfortunate.

In our search to find a good solution we found https://katex.org/. Which is much smaller and could most likely be fully bundled.
Our main concern is that MathJax can support a vast feature set of (La)TeX and katex is more concerned with rendering some math related (La)TeX stuff.

I don't think that this should be a problem from my own experience and people I know, which use CodiMD, but maybe someone here as more information and can shed some light on the topic?

**Comment by mrdrogdrog** [comment]
We need MathJax for Reveal.JS

**Comment by DerMolly** [comment]
can be closed I guess…

**Comment by Vap0r1ze** [comment]
where is reveal.js used in this repo?

**Comment by DerMolly** [comment]
Currently reveal.js is only on the roadmap and not yet reimplemented
