### ISSUE TITLE
Don't use CDN for MathJax

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#253]
Right now MathJax is using the Cloudflare CDN to load the extension files. We should change this.

**Which part of the project should be enhanced?**
MathJax in Markdown Rendering

**Is your enhancement request related to a problem? Please describe.**
We don't want to use any CDN.

**Describe the solution you'd like**
Bundle these files too / copy them into the public directory.

**Describe alternatives you've considered**
Use the CDN.

**Comment by truh** [comment]
MathJax was added to the project as npm package here: https://github.com/codimd/react-client/pull/250/files

**Comment by mrdrogdrog** [comment]
Obsolete, as we use KaTeX since #497
