### ISSUE TITLE
readd wrap option to code block

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#255]
**Describe the solution you'd like**
In the current frontend you can wrap a long code block with a `!` like so

```!
When you’re a carpenter making a beautiful chest of drawers, you’re not going to use a piece of plywood on the back.
```

![grafik](https://user-images.githubusercontent.com/3978662/85414250-27613980-b56c-11ea-801c-3a854c6bb4b2.png)

**Comment by SISheogorath** [comment]
I wasn't aware we can do that, amazing!

**Comment by DerMolly** [comment]
I wouldn't know about that, too. But luckily there is the `/features` page…

**Comment by ccoenen** [comment]
O_O

this is really full of surprises!
