### ISSUE TITLE
readd clickable todos

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#261]
**Describe the solution you'd like**
In the new frontend it should be possible to toggle the state of a ToDo-Item in the markdown renderer like in the old frontend.
This functionality is similar to GitHub's approach.

**Additional context**
[the relevant code in `extra.js`](https://github.com/codimd/server/blob/5c45b35a82061a02189801d23e36185088cd1fba/public/js/extra.js#L254)

**Comment by ErikMichelson** [comment]
Find some starting points (typings) in branch `feature/md-render-tasklists`.

**Comment by truh** [comment]
I'm working on this issue.
