### ISSUE TITLE
import editor into component

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#3]
we should import the current implementation of editor into frontend to fully seperate server and frontend

**Comment by mrdrogdrog** [comment]
We can't just import the current implementation. We must reimplement it in react or just don't use the react client for the editor and let the server render the html template.

I think it's a better and cleaner solution to reimplement the whole editor. After the Landing/History-Page is done, we can examine the current editor code and create new tasks. If you agree, then please close this ticket.
