### ISSUE TITLE
Custom branding and/or logo

### ISSUE THREAD

**Issue by dalcde** [codimd/react-client#300]
Allow custom branding of the CodiMD frontend, e.g. `CodiMD @ host` and custom logos.

**Is your feature request related to a problem? Please describe.**
Currently all instances of CodiMD look exactly the same by default. It is helpful to have custom branding to distinguish one self-hosted instance from another

**Describe the solution you'd like**
Have configuration options to specify the "@ host" part and supply custom logos.

**Comment by DerMolly** [comment]
I started implementing this feature:

With an image file:
![Bildschirmfoto von 2020-07-01 12-31-05](https://user-images.githubusercontent.com/3978662/86236811-fa7bda80-bb9a-11ea-99f3-f4ef5118aa2b.png)
![Bildschirmfoto von 2020-07-01 12-31-10](https://user-images.githubusercontent.com/3978662/86236849-09628d00-bb9b-11ea-9d1a-7dfb3e19f32e.png)


Text only:
![2020-07-01_12-30_1](https://user-images.githubusercontent.com/3978662/86236871-0f586e00-bb9b-11ea-9ed3-f859ed86c089.png)
![2020-07-01_12-30](https://user-images.githubusercontent.com/3978662/86236863-0e274100-bb9b-11ea-94e0-c0c2f6f95d8b.png)
