### ISSUE TITLE
Add UI for tags

### ISSUE THREAD

**Issue by InnayTool** [codimd/react-client#312]
Tagging is not very intuitive in version 1.6, so it would be cool to have a UI which adds tags to a note.

**Comment by DerMolly** [comment]
Should this UI be in the editor in the history?

**Comment by InnayTool** [comment]
I think it's more useful in note. If you want to edit the tags you can click on the note and change them, but it's not intuitive to go back to history to change tags.

**Comment by davidmehren** [comment]
A bulk-editor for tags in the note list might also be helpful, if you want to retag many notes at once.

**Comment by DerMolly** [comment]
I think a bulk editor is another issue altogether and should get it's own issue opened. I think this issue can be closed since we're discussing an editor / auto completion for the whole metadata in #314
