### ISSUE TITLE
Readd emoji autocompletion

### ISSUE THREAD

**Issue by davidmehren** [codimd/react-client#316]
[Apparently](https://github.com/codimd/server/issues/233) the old frontend supports emoji autocompletion (even though not in all cases). The new frontend should also do this.

**Describe the solution you'd like**
When starting to type an emoji with `:`, possible emojis should be suggested with a preview. `Tab` or `Enter` should choose a completion.

**Describe alternatives you've considered**
No completion happens :sob: 

**Additional context**

<img width="194" alt="grafik" src="https://user-images.githubusercontent.com/5023650/87185093-725baa80-c2e9-11ea-8699-d7b0a6eb8896.png">

**Comment by davidmehren** [comment]
This could be extended to also support ForkAwesome icons. Instead of inserting the emoji-UTF-8-symbol into the note, `<i class="fa fa-something"/>` would be inserted.

**Comment by DerMolly** [comment]
Apparently we did that in the past via [textcomplete](https://github.com/codimd/server/blob/313eb74ed697c5260df9293b1aefe3695cf65a5a/public/js/index.js#L3107-L3139)
As we don't use jquery anymore that's not a solution for us. But the project provides [@textcomplete/codemirror](https://www.npmjs.com/package/@textcomplete/codemirror), which seem to be made exactly for our use case (see https://yuku.takahashi.coffee/textcomplete/#textcomplete-codemirror)

**Comment by mrdrogdrog** [comment]
Solved by #387
