### ISSUE TITLE
Emoji and fork awesome picker

### ISSUE THREAD

**Issue by InnayTool** [codimd/react-client#323]
To make it easier to add emojis and fork awesome icons it would be helpful to have a combined picker like in the latest riot web versions.
It could be placed on the toolbar on the top of the editor.

**Comment by davidmehren** [comment]
Riot seems to use https://github.com/missive/emoji-mart

**Comment by ErikMichelson** [comment]
I don't see ForkAwesome icons to be implemented in #329 as of now. Emoji-mart currently only supports sprites or single images as "emojis". As we get ForkAwesome as a font, we can't maintain a set of extracted images.

I proposed a pull request in the emoji-mart to support per-custom-emoji css-classes here: missive/emoji-mart#445
With that change we could define the `fa fa-foo` class for the `foo`-custom-emoji and set a blank background image. With a bit of css that results into our wanted result.

**Comment by mrdrogdrog** [comment]
https://github.com/vector-im/element-web doesn't use emoji-mark, as the project seems to be abandoned.  They made their own emoji picker, but it isn't a separate component. We asked them if  there is any chance to extract it.

**Comment by mrdrogdrog** [comment]
Their emoji picker is tied to the sdk :/
We don't want to have the matrix sdk as a dependency (except if we want to build a matrix client into HedgeDoc).
We could extract it but then we'll have to rewrite half of the code to get rid of the matrix sdk.
We could maintain emoji-mart. but that code is awfull and we don't need every aspect.

Conclusion: we build our own simple emoji picker. For the base data we can use https://github.com/milesj/emojibase

**Comment by mrdrogdrog** [comment]
But right now we have an emoji picker so I'm gonna close this issue.
