### ISSUE TITLE
PlantUML support

### ISSUE THREAD

**Issue by davidmehren** [codimd/react-client#324]
Adapted from https://github.com/codimd/server/pull/29.

It would be nice to support [PlantUML](https://plantuml.com/) diagrams. It's a bit ugly as you have to do a [bunch of transformations](https://plantuml.com/de/code-javascript-asynchronous) to the PlantUML markup and send that to your PlantUML server (Java) which gives you a PNG or SVG.

**Describe the solution you'd like**
Ability to use PlantUML code like this:
```
```plantuml
(plantuml code)
\```
```
(please ignore the backslash, I couldn't get a codeblock inside a codeblock to work otherwise)

**Comment by truh** [comment]
I got an implementation here https://github.com/truh/react-client/tree/feature/plantuml

**Comment by mrdrogdrog** [comment]
Open a PR and we'll review it.

**Comment by truh** [comment]
How do we want to deal with opt-in rendering on a third party server? Do we need to consider it at this stage or can we take care of it when react-client has a concept of configuration?

**Comment by mrdrogdrog** [comment]
The react client already has a concept of configuration. it requests the frontend configuration, that is needed for bootstraping the client and the backend configuration, that contains all the instance stuff. We could add the plantuml server address to the backend config.
