### ISSUE TITLE
Night mode detection

### ISSUE THREAD

**Issue by SISheogorath** [codimd/react-client#40]
If we provide a night mode/dark theme for the new frontend it would be fancy to use the CSS based detection which would allow browsers to indicate that users prefer dark themes and CodiMD could pick that up automatically.

Working code for the old frontend exists in this PR of mine: https://github.com/codimd/server/pull/339

**Comment by HerHde** [comment]
Yeah, if we additionally add the option to set it manually like
`[ dark | auto | light ]`
