### ISSUE TITLE
Re add PDF Export Menu Item

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#401]
This should open a Modal which explains why this feature is currently not supported and how to print to PDF with various browsers. Most likely this would be done via some external tutorial.

**Comment by ErikMichelson** [comment]
The pdf export is already deprecated for quite some time. I don't think re-adding the button is any helpful but connotes that the export itself will be re-added in the future. 

I heard of ideas to support some kind of pandoc integration, maybe that's the better way to go (for 2.1 for example).

Opinions on this?

**Comment by mrdrogdrog** [comment]
This sounds like a "Not implemented yet" modal. And tbh.. I don't like them. They are annoying because you think "Oh! cool! They added this... oh no they didn't -_-"

**Comment by mrdrogdrog** [comment]
We can add basic print capabilities.. But imho a better place for such information would be a FAQ.

**Comment by DerMolly** [comment]
I guess this can be closed, then?

**Comment by davidmehren** [comment]
After the question "why is the PDF export missing" came up multiple times, the idea of explaining the background to our users was born. I still think this would be a sensible thing to do. If you don't like the idea of adding a modal for that, what about greying out/striking through the entry in the export dropdown and adding a `Why?` hyperlink (linking to the corresponding FAQ entry) next to it?

**Comment by DerMolly** [comment]
![image](https://user-images.githubusercontent.com/3978662/89932954-a4c13600-dc0e-11ea-81bf-72239c5f988f.png)
@davidmehren like this?

**Comment by mrdrogdrog** [comment]
> ![image](https://user-images.githubusercontent.com/3978662/89933510-71cb7200-dc0f-11ea-9751-0f4cfe4996a1.png)
> 
> @davidmehren like this?

I think he meant something more like 

~PDF Export~ Why is this disabled? 

With a hyperlink to FAQ page..?

**Comment by DerMolly** [comment]
![image](https://user-images.githubusercontent.com/3978662/89939674-9aa43500-dc18-11ea-918c-2169cd92502c.png)
Like this?

**Comment by DerMolly** [comment]
@davidmehren just said he like this better
![image](https://user-images.githubusercontent.com/3978662/89940096-48afdf00-dc19-11ea-824e-7acf4932f170.png)

**Comment by mrdrogdrog** [comment]
This is confusing, because you say pdf export is unavailable, but you can click it. I would just put a link on the "why?" and use grey font color for the "pdf export is unavailable". This sends the clear message, that pdf export is disabled.

**Comment by DerMolly** [comment]
good point

**Comment by DerMolly** [comment]
![image](https://user-images.githubusercontent.com/3978662/89941297-1a330380-dc1b-11ea-8e58-6287c3c79d7a.png)

**Comment by ErikMichelson** [comment]
This idea was implemented and merged. https://github.com/codimd/react-client/issues/401#issuecomment-672224646
