### ISSUE TITLE
Restructure repository

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#405]
**Which part of the project should be enhanced?**
The directory structure in the repository

**Is your enhancement request related to a problem? Please describe.**
When we started this project we had no idea, how extensive it could be. We only had a bunch of files, mostly components.
Now we have components, layouts, utils, tests, mock data and more. With #360 on the rise we should create a new clean directory structure that is easy to understand for newbies.

**Describe the solution you'd like**
A clean directory structure.

**Describe alternatives you've considered**
Keeping this mess

**Comment by DerMolly** [comment]
Some thoughts:
- [ ] move `external-types` from `src` to `/`
- [ ] abloish `src/landing` and put those folder directly under `src/components` or in `src/components/common`
- [ ] move files inside of `src/utils` to the components that use them or if there are multiple inside `src/components/common/utils`

**Comment by mrdrogdrog** [comment]
I'm against the last point. We should move images, that are needed by components into the component's directory  (or at least into the src directory). If you import images, then we profit from tree shaking. If we put them into the public directory, they will ALWAYS be included, even if we don't use them.
