### ISSUE TITLE
New Permissons screen

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#424]
**Describe the solution you'd like**
According to https://github.com/codimd/server/blob/58e6d91286e8a4ea36c75990f44940ab2610caa3/docs/dev/public_api.yml the note permissions will look something like this

```typescript
interface NotePermissions {
  owner: string
  sharedTo: {
    username: string
    canEdit: boolean
  }[]
}
```

We need to implement an UI for these new permissions. Some thoughts on that:
- We'll most likely show the whole thing either as a flotable object (like the emoji picker) or as a modal
- at the top the owner should be shown. <del>If the current user is the owner, they should be able to give away the ownership of the note (this is intended right @codimd/developers?)</del>
- we should show each entry in `sharedTo` in a line (most likely using `UserAvatar`) with a checkbox for `canEdit`. There should also be an `X` for removing the entry. I think depending on if this is an instant action or needs to be saved later (see further down) we can forego an "are you really sure" dialog here, I think.
- underneath should be an input field here one can enter a username to add to the list.
  - we don't want to leak infos about other users on the system, so no autocompletion on the names.
  - but how will we determine if a username is correct or not? Or do we add anything the user wants and simply let the backend decide what legit? How could we then prevent gaining the information with a lot of requests?
- another question we need to think about: Should the dialog be saving on each change or should there be an dedicated save button at the bottom?

**Comment by InnayTool** [comment]
As we specified the database schema, we saw that the API spec has the flaw that we should add a `sharedToUser` and a `sharedToGroup` attribute. This adds a bit of complexity in the UI but don't change the open questions in general.

**Comment by DerMolly** [comment]
Then we could have two lists. One for users and one for groups.

**Comment by ErikMichelson** [comment]
Just for reference I'm linking #120 .

**Comment by mrdrogdrog** [comment]
Can we please maintain only one issue?
