### ISSUE TITLE
Revision Screen

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#425]
**Describe the solution you'd like**
The current revision screen looks like this 
![grafik](https://user-images.githubusercontent.com/3978662/90317824-612b3c80-df2c-11ea-9cfa-2790888f0e15.png)
We need to implement something like this for this client to.
Currently we only show the timestamp of the revision and it's length as this are the only information in a `NoteRevisionsMetadata` object (see https://github.com/codimd/server/blob/58e6d91286e8a4ea36c75990f44940ab2610caa3/docs/dev/public_api.yml#L686-L700).
Maybe we could also show which users did work on that revision? This would need a change in the way the API works I guess (what do you think @codimd/developers?)

Also as shown in th scrrenshot the ability to revert to a specific revision and to download the note at a specific point in time should be possible. As one can see in `NoteRevision`s (see https://github.com/codimd/server/blob/58e6d91286e8a4ea36c75990f44940ab2610caa3/docs/dev/public_api.yml#L701-L717), we can get the revisions content and a patch from the last revision to the one we selected, so this should be easy enough.

**Comment by SISheogorath** [comment]
> Maybe we could also show which users did work on that revision?

I think we already have this information, we just need to show it: https://github.com/codimd/server/blob/7f71603f280ba9c7ad20839acbd706b27a6b8578/lib/models/revision.js#L92-L100

**Comment by DerMolly** [comment]
Currently we only have that in the give my this specific revision call and not in the list all revisions of this note call. That would need to change to make this possible…

**Comment by ccoenen** [comment]
some versions of diff are ware of file structure, maybe we could also list the closest headline(s) somewhere?

**Comment by DerMolly** [comment]
@ccoenen could you elaborate? I'm not sure I understood what you're meaning…

**Comment by ccoenen** [comment]
If I have a document broken into a few sections, each with a headline

```md
# Amazing Document
## What this document contains
## Why it's amazing
## People who contributed
## Notable Changes
```

And someone changes it

```diff
 ## What this document contains
 ## Why it's amazing
+It illustrates a number of features
 ## People who contributed
```

I would love if the headline preceding it ("Why it's amazing") was part of the list. That might help you find a relevant change more easily than the size or something of the change.

**Comment by DerMolly** [comment]
So in which section did the change occur? Not a bad suggestion. It would need a bit of tweaking since sometimes there are multiple changes in different sections and sometimes the section header is part of the patch, but definitely something to think about

**Comment by ErikMichelson** [comment]
This looks promising: https://praneshravi.in/react-diff-viewer/
