### ISSUE TITLE
Add an own emoji-picker as emoji-mart replacement

### ISSUE THREAD

**Issue by ErikMichelson** [codimd/react-client#430]
**What is your question?**
Currently the react-client uses [emoji-mart](https://github.com/missive/emoji-mart). Because that has neither the current emoji definitions nor is maintained actively, @mrdrogdrog, @DerMolly and me looked for alternatives.
One idea was to use the emoji picker from element-web but as it is heavy integrated into the matrix-react-sdk, that's also no solution.
Even if it's quite some work, we thought that building an own emoji-picker (in a separate repository) is probably the best solution.
As data source we could use this one: https://github.com/milesj/emojibase/

Other opinions on that?

**Comment by mrdrogdrog** [comment]
Another option was to fork and maintain emoji-mart. But that code is awfull and we would have to rewrite half of the code we need.  Also we don't want to maintain the stuff that we don't need.

**Comment by mrdrogdrog** [comment]
Well. We could use the matrix react sdk if we turn HedgeDoc into an collaborative markdown matrix client 😏

**Comment by mrdrogdrog** [comment]
https://github.com/nolanlawson/emoji-picker-element

**Comment by ccoenen** [comment]
I have also raised the question in riot, if this is a must-have / must replace for 2.0. Especially if it becomes neccessary to develop something entirely new, I'd suggest putting this in a release after 2.0.

**Comment by DerMolly** [comment]
That entirely depends on the schedule for 2.0 if we target a release in December or so, yes. If the release is more in the vain of April 2021 we‘ll have time to do that for 2.0.

**Comment by mrdrogdrog** [comment]
TBH: we're running out of issues that are 2.0 relevant but can be solved until the backend is ready. So there is a good chance that this issue will be part of 2.0.

**Comment by mrdrogdrog** [comment]
> https://github.com/nolanlawson/emoji-picker-element

This picker doesn't support custom css classes for emojis, which is necessary for fork-awesome. Who wants to create an issue or talk to the dev? @ErikMichelson  ?
