### ISSUE TITLE
List of all available documents

### ISSUE THREAD

**Issue by rastapopougros** [codimd/react-client#439]
https://github.com/hackmdio/codimd/issues/975

A page with a list of all documents a particular user can access. Maybe only for users who have an account, so it lets us have "secret documents" not publicly listed for anonymous visitors but still open to anyone we send the link.

When connected, before the tab "History", a new tab "All notes", and inside all the accessible notes for me.

**Comment by davidmehren** [comment]
In 2.0, a note can be shared with you or a group you are in. These explicitly shared notes should always be displayed to the user (Nextcloud has a "shared with you" area, a similar tab might make sense for us).
Notes can also be shared with "everyone" and "everyone logged in". If such implicit/public shared gets displayed for everyone in their note list, it will probably get cluttered fast. So we should probably separate such a list. Having a public list of all note on an instance also has privacy implications. If we decide to build such a feature it should definitely be opt-in.

**Comment by davidmehren** [comment]
I just noticed that we are already discussing this topic in https://github.com/codimd/server/issues/455, so lets continue there.
