### ISSUE TITLE
Exclude tags (especially images) from document name

### ISSUE THREAD

**Issue by lhw** [codimd/react-client#440]
I recently tried adding a small logo to one of my documents with the ![]() syntax and while that works flawlessly I also noticed that this would display the un-interpreted line as the "document name" in the personal history. That basically makes the title unreadable. Other common markdown tags such as italic, bold etc are already ignored as far as I can tell.

So my feature request would be to remove interpretable tags from the header alltogether.

**Comment by DerMolly** [comment]
I just tested this with an image tag and it shows the alt tag and everything seems in order. But italics and bold are currently shown as `*` and `**` respectively.
