### ISSUE TITLE
Dollar sign in a link title causes incorrect underlining in edit text

### ISSUE THREAD

**Issue by bitinerant** [codimd/react-client#449]
A link title containing a dollar sign, e.g.:
```
[the $20 bill](https://en.wikipedia.org/wiki/United_States_twenty-dollar_bill#/media/File:US_$20_Series_2006_Obverse.jpg)
```
causes the portion after the link to also be underlined in the text being edited, and causes links to not be underlined at all in all subsequent paragraphs.

Escaping the dollar sign with a backslash works around the issue.

Example ([link](https://demo.codimd.org/I0bGesuFRi6BWj5xvg8NFQ#)):
![image](https://user-images.githubusercontent.com/786662/64244639-52a56a00-cf01-11e9-80c5-3377f8877ce5.png)

**Comment by DerMolly** [comment]
This seems to fixed with 2.0

![grafik](https://user-images.githubusercontent.com/3978662/90828122-c2dd1380-e33d-11ea-9359-caeb788f193b.png)

maybe we want to add an e2e test to check that it stays this way? What do you think @codimd/frontend ?
