### ISSUE TITLE
Upgrade to MathJax 3

### ISSUE THREAD

**Issue by davidmehren** [codimd/react-client#454]
While https://github.com/codimd/server/pull/210 fixes compatibility with the latest MathJax 2.7 patch release, we should look into upgrading to MathJax 3. According to http://docs.mathjax.org/en/latest/upgrading/whats-new-3.0.html#package-manager-support it's (among other things) more compatible with Webpack, so that might make things easier.

**Comment by DerMolly** [comment]
The update of MathJax 3 is already done in the new frontend for 2.0, so I'll close this issue
