### ISSUE TITLE
Edit default note text

### ISSUE THREAD

**Issue by sunjam** [codimd/react-client#464]
Hi, I'd like to be able to edit default text show when a new note is created, before the user begins typing.  [See this forum discussion](https://community.codimd.org/t/how-do-i-modify-new-note-text-description/126/2).  Wondering if this could be customized in a manner that survives Docker pulls.  Thanks!
![Screenshot_20200424_184913](https://user-images.githubusercontent.com/1787238/80271190-d10e7200-8672-11ea-951d-c26d83d7d5e5.png)

**Comment by DerMolly** [comment]
The extra call to get the placeholder.md file is a concern worth weighing.
Makeing `placeholder.md` work would necessitate another field in the config call to the backend, when as @SISheogorath pointed out `default.md` is probably sufficient for your needs. The file `default.md` gets read each time a note is created and used as the default text, which happens in the server automatically. To be fair the content of each note would start with this content and user would need to select everything an delete the default content, but I think this a okay compromise. I'll close this issue as I think we won't add this feature to 2.0. Feel free to reopen this if you think it's necessary to implement this @sunjam .
