### ISSUE TITLE
Markdown render error

### ISSUE THREAD

**Issue by xf-** [codimd/react-client#467]
In this special case with indent afterwards will case a rendering issue with checkboxes.

### Demo
https://demo.codimd.org/BNKA9JAnTb28a1nOlgMJ7Q#

### Content
```markdown
## Header
- [ ] test test test 
- [ ] test test test
    - test `te` st `test` a
    - test `te` st `test` a
- [ ] `foo` test test `bar` boo
    - `test` asdasdasd http://test.test/foo.html
    - `test` asdas http://test.test/foo.html


    `test`
```

### Screenshot
![image](https://user-images.githubusercontent.com/1295633/84576623-7d88ec80-adb6-11ea-8cff-600030a64207.png)

**Comment by mrdrogdrog** [comment]
I tested your example code in the new frontend and everything seems to be fine. As this is no longer relevant for the react frontend I'm going to close this issue.
