### ISSUE TITLE
A context/additional menu should not use a burger menu button

### ISSUE THREAD

**Issue by SISheogorath** [codimd/react-client#492]
**Which part of the project should be enhanced?**

The note history view.

![Current look of the history page](https://user-images.githubusercontent.com/8719867/91355656-c4e81c00-e7ee-11ea-9b8a-8ddaf36d315f.png)

**Is your enhancement request related to a problem? Please describe.**

As you might notice the cards as well as the list view over-use  the burger-menu icon. This icon usually represents the main menu icon of the page for navigation. For sub menu or object options the 3 dots  (also known as kebab, sushi or snowman menu) are normally used.

![burger menu in the wrong place](https://user-images.githubusercontent.com/8719867/91356591-31afe600-e7f0-11ea-844a-863d4cc2e1d0.png)

**Describe the solution you'd like**

Using the 3 dots icon like everyone else for those tiles.

![3 dots on GitHub](https://user-images.githubusercontent.com/8719867/91355875-17293d00-e7ef-11ea-8f8b-142fd5845e7e.png)

![3 dots in Firefox](https://user-images.githubusercontent.com/8719867/91356099-65d6d700-e7ef-11ea-98b8-cc2fa5d4e158.png)

**Describe alternatives you've considered**

No further alternatives considered. It's standard, we should follow that standard.

**Additional context**

**Comment by ErikMichelson** [comment]
It would look like this:

![image](https://user-images.githubusercontent.com/52606896/91671385-7c01d180-eb26-11ea-83fc-cc7f8c9b8825.png)

I'm unsure if the three dots are visible enough.

**Comment by mrdrogdrog** [comment]
(@ErikMichelson I would use the vertical dots instead of the horizonal. They fit more into the symmetry 😅)

**Comment by ErikMichelson** [comment]
That would be like this:
![image](https://user-images.githubusercontent.com/52606896/91701810-1cccad00-eb78-11ea-9dbf-22142ffdba38.png)

Note that the button is a bit wider now. This is due to me setting the icon to fixed-width; otherwise the button would be too narrow.

(Btw the change currently resides in branch [`enhancement/history-menu-icon`](https://github.com/codimd/react-client/compare/enhancement/history-menu-icon))

**Comment by mrdrogdrog** [comment]
Iirc we used the option dots when we created this cards. But I don't know why we changed that icon to the burger menu bars.

**Comment by DerMolly** [comment]
I think @InnayTool or @davidmehren asked for that, because it was not clear what's hiding behind the button.

**Comment by davidmehren** [comment]
I don't recall asking :smile:, but the change is fine by me.

**Comment by SISheogorath** [comment]
I'm definitely happy with the 3 vertical dots version. Looks way better and makes more sense to me. :+1:
