### ISSUE TITLE
Make markdown-renderer more modular

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#496]
**Which part of the project should be enhanced?**
The markdown renderer component

**Is your enhancement request related to a problem? Please describe.**
Right now we have only one markdown renderer component. It's pretty big and complex and implements all the features, we need for the main rendering. (e.g. Scroll tracking, every markdown aspect, meta data change).
However, there are some other parts of the software, where we also need a markdown renderer, but not every feature. (e.g. the help dialog or the front page (https://github.com/codimd/react-client/issues/125))
 
**Describe the solution you'd like**
Split the all-in-one markdown renderer component into a more modular system, so the we can create multiple more lightweight components.

**Comment by DerMolly** [comment]
I think all the render feature should always be included. Things that are only used in the main thing are
- scrolling
- meta data changes
- checking todos

**Comment by ErikMichelson** [comment]
Maybe we should make the one-click-components optional?

**Comment by mrdrogdrog** [comment]
@ErikMichelson thats nothing the renderer decides, but the replacers.

**Comment by mrdrogdrog** [comment]
I also thought about providing the replacers/markdown-it-plugin (or a function that sets them up) as prop.

**Comment by mrdrogdrog** [comment]
Closed via #552
