### ISSUE TITLE
Add graphviz diagram type

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#513]
This Issue is an sub-issue of #257

Codimd supported [graphviz](https://graphviz.org/) diagrams.
It used [viz.js](http://viz-js.com/), which is an wasm port of  the graphviz C code. It's hacky as hell and we don't want to use that anymore.
Now we have three options:

- Use viz.js (and burn our hands afterwards)
- Drop it (like it's hot)
- Use the original graphviz on the server to render the images and grab them via HTTP (like plantuml)
- Do it like #488 and parse the [DOT language](https://www.graphviz.org/doc/info/lang.html) to convert it into e.g. [mermaid](https://mermaid-js.github.io/mermaid/#/flowchart).

I prefer the last option.

(sry for the puns. It's late and I'm tired.)

**Comment by ErikMichelson** [comment]
If possible, I would prefer the last option (parsing DOT and feeding it to mermaid) most.

**Comment by mrdrogdrog** [comment]
https://github.com/SAP/chevrotain *o*

**Comment by DerMolly** [comment]
We started work on the transpiler to mermaid, but found the use of d3-graphviz to be acceptable. It's using wasm graphviz code as well, but it's also feature complete. Mermaid would only have the basics…
