### ISSUE TITLE
Add support for title-attribute-syntax in images

### ISSUE THREAD

**Issue by ErikMichelson** [codimd/react-client#518]
**Describe the solution you'd like**
The following input `![alt text](https://dummyimage.com/48 "example image")` should render as an img-tag with included title-attribute set to "example image".

**Describe alternatives you've considered**
Dropping this 1.6 feature. But why should we?

**Comment by ccoenen** [comment]
does this conflict with setting the size of the image?

Examples here: https://demo.codimd.org/ur22hinERIOEG79PyGA-_w?both

**Comment by ErikMichelson** [comment]
In 1.6 it did not conflict as I just edited it into your demo-document. In 2.0 it shouldn't conflict of course too.

**Comment by mrdrogdrog** [comment]
It shouldn't conflict, because the sizing starts with an equal sign. That's an easy regex adjustment.
