### ISSUE TITLE
remove stock create-react-app title, icons etc.

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#56]
- [ ] the name and description in `public/index.html` should be changed to reflect CodiMD
- [ ] the icons should be changed to the CodiMD Logo
- [ ] the web app manifest should be updated

**Comment by mrdrogdrog** [comment]
Which codimd logo?..

**Comment by DerMolly** [comment]
the current one?

**Comment by DerMolly** [comment]
We could also wait on this until a new name and logo is found

**Comment by mrdrogdrog** [comment]
I think we can wait.

**Comment by mrdrogdrog** [comment]
I suggest using https://realfavicongenerator.net/ for the icons and meta tags as soon as we have an icon.
