### ISSUE TITLE
Replace moment.js

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#586]
**Description**
Unfortunately moment.js has [announced that they will no longer update their lib](https://sebastiandedeyne.com/moment-js-thank-you-for-your-service/). We should consider replacing this dependency in the near to medium future. They were so kind to [recommend some libraries](https://momentjs.com/docs/#/-project-status/recommendations/) for their users.

![grafik](https://user-images.githubusercontent.com/3978662/93686828-4d3da200-fab9-11ea-81ec-e63d0367502a.png)

**Comment by DerMolly** [comment]
Apparently cypress has a momentjs dependency.

https://github.com/codimd/react-client/blob/005c80ff55d4e27c1715268adf05ddf3d15d2dc8/yarn.lock#L4773-L4783

**Comment by ccoenen** [comment]
Here's what the project themselves actually wrote: https://momentjs.com/docs/#/-project-status/

> We now generally consider Moment to be a legacy project in maintenance mode. It is not dead, but it is indeed done.

I see no _immediate_ reason to switch. Moment works. It will continue to work for quite some time.
