### ISSUE TITLE
Collapsible blocks

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#604]
**Describe the solution you'd like**
While working on some renovate PRs I noticed, that github supports collapsible blocks. IMHO this is a very handy feature.

**Describe alternatives you've considered**
don't add it.

**Additional context**

![image](https://user-images.githubusercontent.com/6124140/94335833-8a84c100-ffde-11ea-8946-a31fa544493a.png)

**Comment by DerMolly** [comment]
Which blocks should be collapsible? Code blocks? Each section? And should this be possible in the rendered view only or in the codemirror, too? Does this need changes in the scroll behavior?

**Comment by mrdrogdrog** [comment]
GitHub hast a special block for that in the markdown. I would do it the same way.
I would only affect the renderer.
It wouldn't affect the scroll behaviour, because the line marker positions will be recalculated on size change.

**Comment by ErikMichelson** [comment]
I'm unsure if we should really add special markdown-ish syntax for this, when all needed for this is a very simple piece of HTML.

```html
<details>
    <summary>This is the toggle-label</summary>
    This is hidden by default.
</details>
```

**Comment by SISheogorath** [comment]
I think we shouldn't add a special syntax but a button for such a snippet. One doesn't need it very often, but it would be nice to have it quickly accessible. Alternatively one could add a auto-complete function that provides the snippet.

**Comment by mrdrogdrog** [comment]
Sry I was wrong. Github also uses the HTML block for that. (I didn't know that this tag exists)
Therefore we don't need a new syntax. But autocompletion would be nice.

**Comment by ImaCrea** [comment]
thanks for the tip :)
