### ISSUE TITLE
Add API Key Interface in profile page

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#647]
**Is your feature request related to a problem? Please describe.**
It should be possible to add new api keys for the user in the profile page.

**Describe the solution you'd like**
There should be an interface in the profile page to add a new api key with a name. (the api key should be generated on the backend and then send to the frontend). If a new api key is added the key should be shown beneath the adding interface. Beneath that there should be a list with all the names of the active keys and a button to delete them next to it.
   ```
   +--------------------------------------------+
   |     <inpur>                                |
   +--------------------------------------------+
   +-----------+
   |  Add   |
   +-----------+
+----------------------------------------------------------+
|    The api key withe name 'def' was added                |
|          The key is:                                     |
|         123456789                                        |
|                                                          |
|                                                          |
|                                                          |
+----------------------------------------------------------+

                         +----------+
   abc                   |  Delete  |
                         +----------+

                         +----------+
   def                   |  Delete  |
                         +----------+
```

**Additional context**
How should the API Keys be generated?
- uuid?
- 256-bit random as base64

**Comment by mrdrogdrog** [comment]
> Additional context
> How should the API Keys be generated?
> 
> uuid?
> 256-bit random as base64

That's not our problem, because the server will generate the api keys.
