### ISSUE TITLE
fold gutter does not show

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#649]
**Description**
In 1.6 it is possible to fold code blocks, despite us importing stuff for that it seems to be broken in 2.0.

1.6
![image](https://user-images.githubusercontent.com/3978662/95178103-4b652580-07bf-11eb-9a3b-5c2d271de645.png)
![image](https://user-images.githubusercontent.com/3978662/95178187-6899f400-07bf-11eb-8a5b-0d7e027ebc86.png)
2.0

**Comment by mrdrogdrog** [comment]
Seems like a code mirror plugin is missing

**Comment by mrdrogdrog** [comment]
Seems like a code mirror plugin is missing
