### ISSUE TITLE
Move editor content value into redux state

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#650]
**Which part of the project should be enhanced?**
Editor view code

**Is your enhancement request related to a problem? Please describe.**
Right now we pass the document content (or functions for modifing it) up and down the react dom. That makes the code more complex than it have to be.

**Describe the solution you'd like**
Move the editor content into the redux state. Every component that needs it can subscribe to it and we have less complexity.

**Comment by DerMolly** [comment]
this sounds like a good idea and should be implemented once we close all current PRs
