### ISSUE TITLE
Toggle markmap bindings

### ISSUE THREAD

**Issue by mrdrogdrog** [codimd/react-client#651]
**Which part of the project should be enhanced?**
The markmap component.

**Is your enhancement request related to a problem? Please describe.**
If you scroll through a document with a markmap inside the scrolling stops because markmap uses the scroll event for zooming. This is annoying. But because Mindmaps can get rather big it would be also bad to disable the bindings.

**Describe the solution you'd like**
Add a button to every markmap that enables/disables the zooming.

**Comment by DerMolly** [comment]
the default should be disabled
