### ISSUE TITLE
Add missing API Calls

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#7]
We'll need to write api calls for the openapi spec.

https://github.com/codimd/server/pull/367

**Comment by DerMolly** [comment]
fixed by #84

**Comment by ErikMichelson** [comment]
I wouldn't close this issue. We just implemented the history API spec, but other parts of the API such as for the profile page or editor related ones aren't fully implemented yet.

**Comment by DerMolly** [comment]
maybe we should open a new Issue for those?

**Comment by mrdrogdrog** [comment]
I would let this issue be closed. It had a too general title for two specific tasks (even if the description was missing).

If you have independent tasks (which was the case here), then I prefer multiple issues for atomic tasks. Because then you can close these issues with PRs.

**Comment by mrdrogdrog** [comment]
With atomic issues I don't mean:
- create get for history  (issue)
- create post for history (issue)
- create get for profile (issue)
- create post for profile (issue)

I mean:
- create history api (one issue)
  - create get
  - create post

- create profile api (another issue)
  - create get
  - create post
