### ISSUE TITLE
Improve background-color

### ISSUE THREAD

**Issue by ErikMichelson** [codimd/react-client#71]
The app currently uses bootstrap's default `bg-dark` background. This does not fit well into the CodiMD theme especially regarding the dark cards as in #53.
We should consider changing this color again.

**Comment by HerHde** [comment]
Maybe we should create a bit of a style guide at all.

I personally don't like the mix up of different dark colour tones, like the red-ish and blue-ish dark we had before either and would strongly prefer lightness to create the necessary contrast.

BTW: https://uxplanet.org/8-tips-for-dark-theme-design-8dfc2f8f7ab6 incl. the references

**Comment by HerHde** [comment]
I just found the [background gradients](https://getbootstrap.com/docs/4.5/utilities/colors/#background-gradient), which are disabled by default. Experimenting with this and `.bg-secondary`:

![image](https://user-images.githubusercontent.com/7630662/82771144-4e2c3300-9e3b-11ea-8e02-e3f53087a04b.png)


Note that the enabled background gradient affects buttons which use the Bootstrap button colour classes, like `.btn-primary`.

**Comment by DerMolly** [comment]
Not really a fan of the background gradient

**Comment by mrdrogdrog** [comment]
Currently we are using the default bootstrap theme, because right now we are focusing on functionality. (Re)designing comes later. 

Instead of "Improve background-color" I would rather "Create/Find a bootstrap theme that fits codimd"
