### ISSUE TITLE
Add ability to delete notes directly from history

### ISSUE THREAD

**Issue by ErikMichelson** [codimd/react-client#79]
**Which part of the project should be enhanced?**
The history page.

**Is your enhancement request related to a problem? Please describe.**
Not directly, sometimes I heard about people complaining about having notes deleted from their history while the note still resides on the server, which could be a privacy problem.

**Describe the solution you'd like**
After clicking the delete/cross icon on a note in the history overview, a modal dialog should open where the user may choose between deleting the note from the server or just removing it from the history.

**Describe alternatives you've considered**
Make the fact more visible that a deleted entry from the history does not mean that the note itself was deleted.

**Comment by DerMolly** [comment]
Would two buttons on the Card itself help? Maybe an cross and a trash can? Or would that complicated the UX and make it not understandable?

**Comment by mrdrogdrog** [comment]
If you add a tooltip then It would be more relatable. But yes. I would prefer the two buttons. 
Or: What about a dropdown? If you click the trash can, then you get a dropdown with "Delete note from history" and "Purge note" or something like that.

**Comment by SISheogorath** [comment]
![image](https://user-images.githubusercontent.com/8719867/83752308-a0096000-a668-11ea-9b82-7fdd62058854.png)

I think a general dropdown menu that contains all those options as firefox does it on their `about:newtab` page, seems appropriated and the easiest way to go.

**Comment by DerMolly** [comment]
Menu Icon https://forkaweso.me/Fork-Awesome/icon/ellipsis-h
Upload Icon https://forkaweso.me/Fork-Awesome/icon/cloud-upload/
Remove / Hide Entry Icon https://forkaweso.me/Fork-Awesome/icon/archive
Delete Icon https://forkaweso.me/Fork-Awesome/icon/trash-o
