### ISSUE TITLE
Add no-focus class for bootstrap button components

### ISSUE THREAD

**Issue by ErikMichelson** [codimd/react-client#83]
**Which part of the project should be enhanced?**
The editor, but the css rule might be defined globally.

**Is your enhancement request related to a problem? Please describe.**
In the current `feature/editor` branch, the mode-toggle buttons have an outline focus after clicking them.

![image](https://user-images.githubusercontent.com/52606896/83254551-3e03b300-a1af-11ea-8cba-42934add2758.png)

**Describe the solution you'd like**
Add a `no-focus` class, that can be applied to these buttons (and maybe other ones).

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

**Comment by mrdrogdrog** [comment]
Bootstrap uses the class `.focus` (maybe even :focus) for showing this border. We could add a new class to the index.scss, that overrides this bevahiour and removes this border.  This class can then be used on components like the EditorViewToggleButton

**Comment by mrdrogdrog** [comment]
Won't fix this, because the focus is essential for keyboard navigation.
