### ISSUE TITLE
History - Import / Export

### ISSUE THREAD

**Issue by DerMolly** [codimd/react-client#88]
Tilman and I were just thinking about the history.

Currently there are a local history (for non-logged-in users) and a server history.
There is also the possibilty to import and export the history, which we can't find any use for, beyond exporting local history and server history to fiddle with the json-files and then reimport it. (Basically a manual db operation for the user)

We thought about, if that is really necessary. Maybe we can show the local history and the server history together (and filter which you want to see optionally).

Mark the local history entries (maybe as 'not synced' [a red sync icon] or something) and add the possibilty to move them to the server history via a button. Maybe also make the opposite (server -> local) possible [Is that really useful?] ?

An history entry would have the following UI elements then:
  - storage icon (you can choose one(maybe both?) storage location )
      - :computer: local - so you can see it if you're either logged in or logged out
      - :arrows_counterclockwise: server - so it would be linked to your account
  - pin icon
      - pin the note
  - delete icon
      - delete entry from history
      - nuke note entirely

With that we could remove the need for the import / export feature entirely at least that's what we think...

What do you think?

**Comment by SISheogorath** [comment]
The import/export feature is quite useful for migrating users. BUT: When reworking logins around a central account with multiple authentication things, this should solve itself.

But I recommend to throw that into the CodiMD community chat and see if end-users my have a usecase.

**Comment by mrdrogdrog** [comment]
We threw it into the community chat and some people brought up use cases like "I want to back up my history". 
As far as we can see the feature is still wanted and should be added.
