### ISSUE TITLE
Handling RTL

### ISSUE THREAD

**Issue by BoFFire** [codimd/react-client#89]
**Description**
For now the UI is not yet supporting right-to-left display mechanism of the UI such as the login page and the top menu.

**Expected behavior**
Depending on the language set in the the user's browser `user-agent` the UI should be displayed the right way such as in arabic, hebrew an farsi languages.

Best regards,

**Comment by BoFFire** [comment]
Ping @DerMolly :)
I'm not a coder, just a translator but can help with testing and screenshots.

**Comment by DerMolly** [comment]
Maybe this is an idea to try as a first try https://stackoverflow.com/questions/14193382/css-reverse-a-whole-website-mirror-effect

**Comment by DerMolly** [comment]
What do you think @BoFFire ?
![image](https://user-images.githubusercontent.com/3978662/83949203-a93e2c80-a822-11ea-853b-fa987c09a199.png)
![image](https://user-images.githubusercontent.com/3978662/83949208-b1966780-a822-11ea-8844-9c11647968d9.png)

**Comment by BoFFire** [comment]
Ping @ahangarha I think that we don't have to flip the editor and the viewer. What do you think? Any Advice ?

**Comment by BoFFire** [comment]
May be we have just to aligh some elements only.
Waiting for @ahangarha advice.
![Capture+_2020-06-06-17-56-14](https://user-images.githubusercontent.com/42316180/83949996-4ac37f00-a81f-11ea-817d-9b8084e036d7.png)
![Capture+_2020-06-06-17-57-56](https://user-images.githubusercontent.com/42316180/83950001-544ce700-a81f-11ea-9e9c-fbaa130cb3a6.png)

**Comment by ahangarha** [comment]
The general rule as per my understanding is to add `dir="auto"` to all elements that can contain text which can be RTL or LTR. This makes browser decide the direction of the given element based on the first character.

I am trying to run the app in dev mode but running `yarn install` gives me this error:

`00h00m00s 0/0: : ERROR: [Errno 2] No such file or directory: 'install'`

If someone can help me, I would love to help

**Comment by mrdrogdrog** [comment]
@ahangarha Did you step into the directory with `cd` after git clone? (I know this is a dumb question, but some people forget this, because it's not in our README yet)

**Comment by mrdrogdrog** [comment]
@ahangarha It's not only about text. We have to rearrange some elements like buttons, which start on the left on some screens.

**Comment by mrdrogdrog** [comment]
@BoFFire, why did you mark the icons on the right? Is that wrong?

**Comment by ahangarha** [comment]
I managed it with NPM. But the app doesn't work properly which I guess is due to being in very early development phase.

With the help of my add-bidi-support addon and few extra tweaks, it seems I am getting very good results. I will share it soon.

**Comment by BoFFire** [comment]
> @BoFFire, why did you mark the icons on the right? Is that wrong?

It is correct :)
