### ISSUE TITLE
"Delete" should not be part of the permissions menu

### ISSUE THREAD

**Issue by ccoenen** [codimd/react-client#91]
One thing that always bugged me about the permissions menu is, that it contains deletion. I would like to suggest to remove it from there and put it into the other menu.
(screenshots from legacy codimd frontend)

![grafik](https://user-images.githubusercontent.com/124909/83328196-868ba100-a281-11ea-89f3-73a58c5eeec1.png)

![grafik](https://user-images.githubusercontent.com/124909/83328214-aa4ee700-a281-11ea-88de-74cf2b57d7fd.png)

**Comment by mrdrogdrog** [comment]
Good Point.

**Comment by truh** [comment]
Looks like this is already done.

![Screenshot from 2020-07-05 12-13-07](https://user-images.githubusercontent.com/1183303/86530436-fdd3d680-beb8-11ea-9fde-8673ab7da2ba.png)

**Comment by ccoenen** [comment]
thanks :-)
