### ISSUE TITLE
Sticky edit mode

### ISSUE THREAD

**Issue by ccoenen** [codimd/react-client#92]
Edit mode could be "sticky". Personally, this would make a ton of sense to me. I am usually in reading mode for most things I do, or I am in writing mode for most things I do.

So having a button that would also extend to links I click within codi (when I am editing document "A" and click a link to document "B", I would mostly like that to be also in editing mode. When I started out in view mode, I most likely like the target document to be in view mode as well).

**Comment by DerMolly** [comment]
Instead of making the mode sticky, we could just add an option to the users profile, to set an default. Maybe add an right click option to the mode changer or something so quickly change this in the editor. This would work on different machines with the same user. Anonymous users can't set a default with this procedure, but I think that's fine since it's more of a power user feature anyway.

Parameters in the URL should probably still have presedence, because that's the intended mode for the viewer.

**Comment by ccoenen** [comment]
yes, the url parameters are probably more important than a default.

putting this setting in the profile is not exactly my preference, to be honest. I would change this setting twice a day, probably (I'm often in "edit" mode for quite a while and after that I'm in "review" mode for a little while longer). But this is not for me alone, I'd let this sit here for a little bit of discussion.

**Comment by DerMolly** [comment]
The rightclick options in the mode changer is intended or heavy users like yourself

**Comment by ErikMichelson** [comment]
Wouldn't it be possible to just remember the editor mode in the localstorage of the browser? This would be similar for logged-in users and anonymous users, and we wouldn't add a "hidden" feature that only works by right-clicking.

**Comment by DerMolly** [comment]
The idea was to put that in the profile page and (for quick access) in the mode changer…

**Comment by ErikMichelson** [comment]
TBH: I don't like the idea of tying this to the profile or to logged-in users in general. I think we should minimize the necessary database changes if possible, adding fields for things like the default mode per user seems unreasonable for me. As I stated above I would prefer a per-browser solution that just remembers the last clicked mode.

**Comment by mrdrogdrog** [comment]
Wait a second. I think you are discussing two different things.
You are discussing: "If I switch the mode then EVERY opened doc I open, even if I opened it from the history, should have the last used mode"
@ccoenen describes "If I'm in a document and use view/edit mode and then click a Link to another document, the opened document should have the same state"

Right?

Because the second one doesn't need to have a global state like localstorage or something. We just have to adjust the links to other documents.

**Comment by ccoenen** [comment]
Please do not mess with links to other documents, this is not what I had in mind.

How would you even determine which links to change and which to keep the same? There's an infinite number of ways this could go wrong.

A thing like "my profile has a setting" or "localstorage know" is _much_ easier and describes pretty well what I had in mind.

Basically this would be the heuristic:
- Does the URL contain some overriding factor (legacy codimd had this as `?edit`, `?view`, `?both`.)? -> use the thing requested by the url.
- Does the localstorage prefer something? -> use that
- neither? -> default to view mode

**Comment by mrdrogdrog** [comment]
But that's what you described.

> when I am editing document "A" and click a link to document "B"

I wouldn't change the links permanently in the document. I would alter them in the rendering.

**Comment by mrdrogdrog** [comment]
but okay.

My 2 cents:
I like the idea @DerMolly  described. I would separate "I want to see the document in view mode NOW" and "I want to see every document (that has no parameter in the URL) with THIS default setting".

**Comment by ccoenen** [comment]
> 
> But that's what you described.
> 
> > when I am editing document "A" and click a link to document "B"

Yes I wrote "if I click a link" because that is what i do. I did _NOT_ mean to change that link. Just to view the resulting document in a different way.

> I wouldn't change the links permanently in the document. I would alter them in the rendering.

Do not do this. This path lies madness.

Which one of these would you alter and why?

```txt
[test1](/test1)
[test2](https://example.com/test2)
[test53](https://other.example.com/test53)
[test3](./rggzguRSSdavsvEDJf2dnw?both)
[test4](/imprint)
[test5](/forums)
```

you cannot know which of these will be CodiMD (and therefore would have to be altered) and which ones are not. Either one of these could be anything.

**Comment by DerMolly** [comment]
I meant there is a default per user, but you of course can change the viewMode at anytime to anything you currently need, then if you hard reload it would fall back to the users default.

**Comment by ErikMichelson** [comment]
But opening another document in a new tab or browser window is the same as hard-reloading, isn't it? In that case that solution will always fallback to the user default...

**Comment by mrdrogdrog** [comment]
> > But that's what you described.
> > > when I am editing document "A" and click a link to document "B"
> 
> Yes I wrote "if I click a link" because that is what i do. I did _NOT_ mean to change that link. Just to view the resulting document in a different way.
> 
> > I wouldn't change the links permanently in the document. I would alter them in the rendering.
> 
> Do not do this. This path lies madness.
> 
> Which one of these would you alter and why?
> 
> ```
> [test1](/test1)
> [test2](https://example.com/test2)
> [test53](https://other.example.com/test53)
> [test3](./rggzguRSSdavsvEDJf2dnw?both)
> [test4](/imprint)
> [test5](/forums)
> ```
> 
> you cannot know which of these will be CodiMD (and therefore would have to be altered) and which ones are not. Either one of these could be anything.

I would keep the links as they are in the original markdown. But in the translation from markdown to html (which is local), I would adjust the links that are refering to other documents on this codimd instances.

**Comment by mrdrogdrog** [comment]
I think we are still not talking about the same thing.

Do you want a default setting for opened documents?
Do you want to keep the current view mode for every document that is opened from the current one?
Do you want to keep the current view mode for every document that is ever opened after this one, regardless where the origin of the link is?

I'm strictly against "If I change the view mode in this document, then every document that will be opened after this one will have the same view mode".

**Comment by ccoenen** [comment]
Altering links is _also_ not the way to go because links could come from anywhere. Company chat, wiki pages, forums, github issues. Do not alter links. Not in rendering. This is not the solution.

My suggestion is the very simple three step thing I described in https://github.com/codimd/react-client/issues/92#issuecomment-636441740

- Does the URL contain some overriding factor (legacy codimd had this as `?edit`, `?view`, `?both`.)? -> use the thing requested by the url.
- Does the localstorage prefer something? -> use that
- neither? -> default to view mode

I will add that the overriding factor should never be added by anything, also just not on rendering as suggested above.

> > Which one of these would you alter and why?
> > 
> >     [test1](/test1)
> >     [test2](https://example.com/test2)
> >     [test53](https://other.example.com/test53)
> >     [test3](./rggzguRSSdavsvEDJf2dnw?both)
> >     [test4](/imprint)
> >     [test5](/forums)
>
> I would keep the links as they are in the original markdown. But in the translation from markdown to html (which is local), I would adjust the links that are refering to other documents on this codimd instances.

You are not answering the original question, that you would _need_ to answer: which of these would you alter (even when it's only in the rendered html)? The Problem is: you can never know which of these is part of CodiMD and which is not. Which is why you should not touch the links in the documents.

> I'm strictly against "If I change the view mode in this document, then every document that will be opened after this one will have the same view mode".

If this is the case, we can close this here. This is exactly what I described.
