### ISSUE TITLE
Reordering ui elements for a clear information architecture

### ISSUE THREAD

**Issue by ccoenen** [codimd/react-client#93]
A lot of the UI elements in CodiMD were thrown in "where there was some space left", or so it feels. I would love to see this rewrite deal with this.

Basically I suggest to have two clear hierarchical zones:

The **top bar** (needs a better name) should be reserved for everything that is of overarching interest in CodiMD

Below that the **document area** (probably also needs a better name) would start with _everything related to the document_. There are some elements that need to be in the document area regardless of edit mode _or_ view mode. So I'm essentially proposing a second bar of UI elements with everything related to the document in between the current main bar and the view/edit zone.

This is a legacy CodiMD Screenshot, basically I think these things should change:
* Keep the **logo** (1)
* Deal with the **mode switcher** (2) once we've discussed #92 (it is then either a global thing and stays there _or_ it is a document thing and moves down a bit).
* **Night mode** (3) is global as far as I know, so it stays there.
* **Help** (4) is global, so it stays there.
* **New Document** (5) is global, so it stays there.
* "**x people online**" (6) is a document level info, this should move to the document area (i.e. Down).
* in its place (7) there should be info on the **currently logged in user** (or the possibility to log in if one is _not yet_ logged in)
* **Publish** (8) should be incorporated into (9) and both belong to the document (i.e. they should move down a bit)
* As mentioned earlier the "**menu**" (9) is only related to stuff about the document, so it should probably *get a different name*. And it needs to move down to the document tools.
* The **permissions** (10) are currently only visible in "view" mode, and I would like to change this. This is document level stuff that belongs with (6), (8) and (9), as such it would be visible regardless of edit or view or both modes. As mentioned in #91, 'delete' should not be in that one but in (9) instead, in my opinion.
* **meta info** on ownership and changes (11) may also belong int that bar, I'm not sure about those.
* (not pictured) the **in-document navigation sidebar** should become part of the document level bar so it is available in edit mode as well

Numbers are color-coded for "general level" (fuchsia), "document level" (turquois) and "undecided" (blue).

![grafik](https://user-images.githubusercontent.com/124909/83328660-f64f5b00-a284-11ea-9689-12a8a807587a.png)

**Comment by mrdrogdrog** [comment]
Solved in #399
